### ISSUE TITLE
refactor asset to assets according to v3.0 schema

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint#84] opened 2022-04-04 13:49 UTC
## Motivation
In order to achieve our goal of using multiple assets for compose decompose we need to refactor almost the entire codebase. In short: The `asset` object that was previously `None` or `{data: <any valid assosiative array>}` was changed to `assets` which consists of the `asset` objects as defined here.

## Todos:
- Analyse codebase and gather all appearences of `asset` or everything that is connected to it
- Document on a per file basis which files use `asset` and how the `asset` object is used
- Create refactoring tickets that can be worked on in parallel

**Comment by LaurentDeMontBlanc** [comment] 2022-04-11 13:10
@ArpitShukla007 I encountered the first hurdle. To validate the `tx_hash` a `tx` is fetched from the db and patched together with the `asset` and `metadata`. At the moment `assets` are stored like so:
```
{
	"_id" : ObjectId("6254223751ca78513ad3fd35"),
	"data" : {
		"name" : "I am created by the create_tx fixture. My random identifier is 0.950064555783776."
	},
	"id" : "5e2e053d48b192c2dade2bbae30a042b7d6a8ed1fb9ab24591092ab58c6595a9"
}
```
As of now the `id` is the same for the `asset` and the `tx` it is connected to. We need to adjust the `asset` so that it has it's own `id` as well as a `tx_id` field for reference.

**Comment by LaurentDeMontBlanc** [comment] 2022-04-12 13:16
@ArpitShukla007 i have changed the `get_assets` method so that it reflects the same behavior as  `get_asset` by omitting the `_id` and `id`

**Comment by ArpitShukla007** [comment] 2022-04-13 07:39
@LaurentDeMontBlanc I have resolved the issue of validation of assets in terms of `validate_txn_obj` and `validate_language_key`. I found that the issue was because of passing the assets as argument instead of passing the whole transaction body. Later, we fetch the asset from `tx_body` dict. Also, need some upgradation in transaction class from `asset` to `assets` that I am doing currently.

**Comment by LaurentDeMontBlanc** [comment] 2022-04-13 09:15
@ArpitShukla007 the issue with the hash validation was that `get_transaction` fetches the assets for a tx. We want this for `CREATE` txs because we need the contents of `assets` (i.e.: the `data` objects) to get the same hash again when validating. This will also be crucial for `COMPOSE`. For `TRANSFER` this is not necessary because the tx obj is already returned with the `assets` in the correct form (e.g.: `assets: [{'id': 'some random id'}]`)

**Comment by ArpitShukla007** [comment] 2022-04-14 05:44
@LaurentDeMontBlanc There was a issue with `unspent_outputs` function of `Transaction` class where for a Transfer operation, id of the asset was to be derived. Now, with the change of the assets structure, its not possible to get id directly from the list, hence, I have added a search logic to fetch the id. This solves the issues of `test_update_utxoset`.

**Comment by LaurentDeMontBlanc** [comment] 2022-04-14 11:23
@ArpitShukla007 I have to check and refactor any occurrences of `backend.query.get_asset()` and `backend.query.get_assets()`. Up until now these remove `_id` and `id` by default. This shouldn't be the case, I will change it so that it has no default filter and calling functions should pass the correct filter for their needs.

**Comment by LaurentDeMontBlanc** [comment] 2022-04-14 14:28
@ArpitShukla007 i have left you some `TODO` comments at places where I think we need to adjust the code to get everything up and running. I've identified 3 types of root errors:
- InvalidHash -> probably caused by `get_transaction` in lib.py. Either on the asset fetching itself or while appending them to the tx 
- Skipped test cases -> some pytest plugins don't function as expected, this needs further investigation
- TypeError: list indices must be integers or slices, not str on generate_election -> there are some calls where a list is passed and sometimes an object

**Comment by ArpitShukla007** [comment] 2022-04-19 06:27
@LaurentDeMontBlanc I found the error showing `fixture 'mocker' not found`. The issue was in the installation of dependencies. After installing `pytest-mock`, the issue was solved.

**Comment by ArpitShukla007** [comment] 2022-04-21 07:18
@LaurentDeMontBlanc I found the similar fixture issues as `fixture 'mocker' not found`. The issue got resolved by reinstalling `pytest` and also additionally installing the `pytest-flask`.

**Comment by LaurentDeMontBlanc** [comment] 2022-04-26 08:29
@ArpitShukla007 i solved the invalid hash issue, however there is a problem that we will probably encounter with `COMPOSE` and `DECOMPOSE`. In `lib.py` the `get_transaction` function fetches assets by transaction id. This suffices for the current transactional types because they either have asset data in the form of `[{data: <any valid assosiative array>}]` or `[{id: <some id>}]`. 

For `COMPOSE` and `DECOMPOSE` there will be a combination of both ids (references to other assets/txs) and data objects (newly created assets). I suggest that we continue continuing on commenting problems here and create tickets for unsolved issues when reviewing this PR

**Comment by LaurentDeMontBlanc** [comment] 2022-04-27 08:59
@ArpitShukla007 we also need to adjust the planetmint-driver. i have created a corresponding branch on the driver repo that we can reference in the `asset-migration` branch

**Closed** 2022-11-02 12:30 UTC
